[book]
title = "Rx Compiler Specification"
authors = ["Compiler Course Staff"]
language = "en"

[output.html]
additional-css = ["theme/reference.css"]
additional-js = ["theme/reference.js"]
git-repository-url = "https://github.com/peterzheng98/RCompiler-Spec"
smart-punctuation = true

[output.html.search.chapter]
"grammar.md" = { enable = false }

[rust]
edition = "2021"

[preprocessor.spec]
command = "cargo run --release --manifest-path mdbook-spec/Cargo.toml"

[build]
extra-watch-dirs = ["mdbook-spec/src"]
